### ISSUE TITLE
PreviousStates periodic compression

### ISSUE THREAD

**Issue by aleskandro** [miratepuffin/raphtory#22]
We can store another (null) map (let's say `toCleanMap`) for each entity; periodically a thread will:
1) Assign to `toCleanMap` the reference of the previousHistory
2) Make a new instance of TreeMap and assign it to previousHistory
3) The worker thread will clean up the `toCleanMap`
4) `toCleanMap` and `PreviousHistory` have to be concatenated and reassigned to `PreviousHistory` at the end of the process. `toCleanMap` will be collected by the GC.

**Comment by miratepuffin** [comment]
Addition of a `Add only' flag which will notify the partition manager to only store the oldest update in the entity manager (properties will remain with full history as all are unique). Possible option of oldest and newest update to decide if the entity should be wiped from memory if there are too many entities within the PM.

**Comment by miratepuffin** [comment]
Compression currently completed my Archivist
